apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-2hrc
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hosy-tenant/rhtap-demo-app/hacbs-test-project-2hrc@sha256:e43752b82e263b2c2c2e9b99ae1ff5968ada92f6354b66c5673431aac2eaa997
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
