apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-2hrc
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hosy-tenant/rhtap-demo-app/hacbs-test-project-2hrc@sha256:0aa5536ce81a9984ef626786787739fddeac3742af4e4c6d45e5aae932062d62
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
